[Back] Image Upload && Image URL GET
sproutt/eussya-eussya-api pull request #141
Opened 2021-03-09 12:22 UTC by Ilisha29

기능 구현

- Image Upload

- Image URL GET

2021-03-14 07:18 UTC, Bellroute reviewed
고생하셨습니다! 테스트 코드 작성하실 때 케이스로 잘못된 접근이나 데이터에 대한 케이스도 추가로 테스트 해보시면 좋을 것 같습니당

코드를 살펴보니 File이라는 엔티티가 가지고 있는 데이터로 멤버 정보, filekey, storagePath가 있는데,
storagePath가 cloud front 도메인 뒤에 filekey만 붙인거라서 크게 두 데이터를 각각 관리해야하는 이유가 있는지 궁금합니다.

그리고 현재는 Member 테이블과 File 테이블이 따로 존재하는데 Member쪽 필드로 이미지 url을 저장하는 profilePath를 추가하는 방법은 어떤가요? 회원 정보 화면에서 회원 정보를 조회한다고 했을 때, 회원 정보 따로 이미지 경로 따로 두 번 요청하게 되거나, db 쿼리에 매번 join이 추가될 것 같습니다. 이 부분은 다른 분들과 다 같이 논의해보고 싶네요!

2021-03-14 07:18 UTC, Bellroute commented on src/main/java/com/sproutt/eussyaeussyaapi/application/file/S3Service.java
> +            String originFileKey = fileService.findByNickName(nickName).get().getFileKey();
findByNickName()을 두 번 사용하여 db에 동일한 요청을 2번씩 하게 되는 것 같습니다. Optional에서 제공하는 메소드를 활용해서 개선할 수 있을 것 같습니다.

http://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/

2021-03-14 07:18 UTC, Bellroute commented on src/main/java/com/sproutt/eussyaeussyaapi/application/file/S3Service.java
> +        String[] strings = filePath.split("\\.");
명확한 의미가 담긴 변수명으로 변경하면 좋을 것 같습니다.

2021-03-15 17:05 UTC, hyukjin-lee requested changes

2021-03-15 17:05 UTC, hyukjin-lee commented on src/main/resources/import.sql
> +INSERT INTO mission (id, title, contents, writer_id, deadline_time, running_time, status) values ( 69, 'mission20', 'mission20 contents', 99, '2020-07-29T03:00', '01:00:10', 2);
불필요한 커밋 같습니다

2021-03-15 17:05 UTC, hyukjin-lee commented on src/test/java/com/sproutt/eussyaeussyaapi/api/file/FileControllerTest.java
> +    @DisplayName("필 업로드 요청")
오타가 있는 것 같습니다

2021-03-15 17:05 UTC, hyukjin-lee commented on src/test/java/com/sproutt/eussyaeussyaapi/api/file/FileControllerTest.java
> +public class FileControllerTest extends HeaderSetUpWithToken {
부모 클래스는 어떤역할인가요?

2021-03-15 17:05 UTC, hyukjin-lee commented on src/test/java/com/sproutt/eussyaeussyaapi/api/file/FileControllerTest.java
> +    @DisplayName("프로필 URL 요청 - 프로필 등록하지 않았던 경우")
~ 경우 ~ 한다 까지 적어주시면 좋을 것 같아요

2021-03-17 15:25 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/application/file/S3Service.java
> +        String[] strings = filePath.split("\\.");
넵 좋은 조언 감사합니다.

2021-03-17 15:26 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/api/config/SecurityConfig.java
> +
커밋 로그 몇개는 PR 올라가는거 확인하려다 불필요한 커밋을 만들게 되었습니다.ㅠㅠ 앞으로는 불필요한 커밋이 있으면 제거하도록 하겠습니다.

2021-03-17 15:29 UTC, Ilisha29 commented on src/test/java/com/sproutt/eussyaeussyaapi/api/file/FileControllerTest.java
> +    @DisplayName("프로필 URL 요청 - 프로필 등록하지 않았던 경우")
넵!!

2021-03-17 15:29 UTC, Ilisha29 commented on src/test/java/com/sproutt/eussyaeussyaapi/api/file/FileControllerTest.java
> +    @DisplayName("필 업로드 요청")
넵ㅎ..

2021-03-17 15:34 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/domain/file/File.java
> +    private String nickName;
nickName을 필요로 했던 이유는 여럿이 있는 채팅방에서 다른 유저의 프로필을 받아와야 하는 경우에 필요할 것이라고 생각해서 필드로 추가하였습니다.

2021-03-19 02:40 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/application/file/S3Service.java
> +        String newFileKey = nickName + infix + fileType + "-" + date.format(new Date());
기존에 문제점이 많았던 Date와 Calendar 보다 자바8부터 적용된 LocalDate 사용이 더 적절하다고 생각합니다.

2021-03-19 05:49 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/application/file/S3Service.java
> +    public AmazonS3 s3Client;
final로 선언하고 자동주입이 되서 그거에 맞춰서 수정했습니다.

2021-03-19 05:56 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/application/file/S3Service.java
> +    @PostConstruct
property 값들이 제대로 들어있을때 생성자 주입으로 자동으로 등록해주는 것을 확인하고 반영하였습니다.

2021-03-19 10:20 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/api/file/FileController.java
> +        File file = fileService.findByNickName(nickName).get();
좋은 의견 감사합니다!!! 덕분에 Optional과 제대로 된 Optional처리에 대해서 조금 알게 됬습니다.

2021-03-19 11:20 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/api/file/FileController.java
> +        File file = fileService.findByNickName(nickName).get();
리뷰 반영시에 고민은 orElse / orElseGet 중 어떤것을 적용해야하는지에 대해였는데
defaultProfileKey 처럼 다른 비지니스 로직에 영향을 주지 않는 변수는 orElse를 사용해도 문제되지는 않지만, null일때만 실행을 되는 orElseGet을 사용하는게 적절하다는 생각으로 orElseGet으로 반영했습니다

2021-03-19 11:29 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/api/file/FileController.java
> +    private static final String defaultProfileKey = "https://dugjnp7kky4tj.cloudfront.net/default_profile.jpg";
넵!

2021-03-20 15:09 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/application/file/S3Service.java
> +            String originFileKey = fileService.findByNickName(nickName).get().getFileKey();
넵 덕분에 Optional에 대해서 좀더 공부하게 되었습니다!!

2021-03-20 15:28 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/application/file/FileServiceImpl.java
> +            return fileRepository.save(file.updateFile(storagePath, fileKey));
넵!!! 알겠습니다!!

2021-03-20 15:32 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/api/file/FileController.java
> +    public ResponseEntity uploadProfile(@RequestHeader HttpHeaders requestHeaders,
requestHeader에 토큰을 담아서 전달하기때문에 없으면 필터에서 걸리게 됩니다!!

2021-03-20 15:39 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/application/file/FileServiceImpl.java
> +        return fileRepository.findByNickName(nickName);
제가 기존에 생각했던것은 사용자가 단체 채팅을 이용중에 있다고 하면 자신의 프로필 URL은 storagePath필드에서 가져올 것이고 나머지는 유저의 nickname으로 다시 요청해야한다고 생각했습니다.(말씀하시고 곰곰히 생각해봤는데 잘 못 생각한것같네요... 이해가 안되실수도...)ㅜㅜ
하지만 단체채팅방의 경우에도
MemberList = 본인 + 다른 사람들 이기에 본인과 같이 객체의 storagePath로 얻을 수 있다고 생각이 들어 불필요해 보일수 있는것 같습니다.

좀 더 생각해보고 필요한 경우가 없다는 확인이 들면 제거 하도록 하겠습니다!

2021-03-20 15:45 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/api/file/FileController.java
> +    private final FileService fileService;
저도 처음에 고민했던게 프로필 관련 비즈니스로직을 한곳에 묶어야하나,
아니면 하나는 s3와의 연동을 위해 다른 하나는 프로필 로직을 처리하는데로 나누어야 하는지 고민했던 부분인데, 프로필을 관련 비즈니스로직으로 같이 처리하는게 좋을 것 같습니다.
왜냐하면 관련된 로직인데 굳이 나누다 보니 s3service에 FileServiceImpl의 의존생기게 되었기 때문입니다.

2021-03-20 16:17 UTC, hotheadfactory commented on src/main/java/com/sproutt/eussyaeussyaapi/domain/file/File.java
> +    private String nickName;
이렇게 파일이 User 엔티티가 아닌 닉네임을 참조하게 되면, 사용자가 닉네임을 바꿀 경우에는 어떻게 처리되게 되나요?
현재는 닉네임 변경 기능이 없지만, 추후 닉네임 변경을 지원하는 경우 닉네임을 바꾼 후 이전에 올린 파일이 잘못 참조되는 경우가 생길 것 같습니다.

2021-03-21 14:47 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/api/file/FileController.java
> +public class FileController {
기존의 생각은 파일이라는 인터페이스를 만들고 프로필을 인터페이스 구현체로 하려고 했었습니다. 하지만 우선 동작하게 먼저 만들자는 생각 때문에 그런생각을 반영시지 못한채로 여기까지 오게 되었습니다.
다음으로 member 도메인의 필드로 넣는것에 대해서는 저 또한 옳다고 생각하였지만, 그렇게 하지못한 이유는 아무래도 협업에 익숙하지 않아 member도메인에 새 필드를 넣고 비즈니스 로직을 추가한다면 혹시나 어쩌다 다른 코드를 건들여서 문제를 일으키지 않을까하는 걱정이 커서 다른 도메인으로 분리하게 되었습니다.
 이부분에 대해서 월요일 시간을 통해 집고넘어가는대로 반영하도록 할 예정입니다!

2021-03-21 14:58 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyaapi/api/file/FileController.java
> +public class FileController {
파일과 관련된 모든 작업들을 인터페이스로 추상화 해버리면 과하지 않을까하는 생각이 드네요.
인터페이스 메서드 시그니처로 인해 에러 던지는 것도 공통 정책으로 가져가야할거고, 메서드 이름들도 로우한 명칭들 밖에 가질 수 없어서 비즈니스를 녹여내기 어려울 듯 하고, 유연성이 많이 떨어질 것 같습니다. 파일로 추상화하면 유연성을 잃는 대신에 얻는 장점이 있을까요?

+ member 도메인의 하위라고 말한 것은 멤버 도메인 모델을 칭한 것이 아니고 member 라는 도메인 패키지를 말씀 드린 것입니다. member 패키지에다가 profile 관련 구현을 하면 되지 않는지? 라는 뜻이었습니다.

2021-03-21 15:08 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/api/file/FileController.java
> +public class FileController {
파일로 추상화하려했던 이유는 프로필만이 아닌 추후에 으쌰으쌰가 스토리지를 프로필만아닌 다른 파일에 대해서도 사용하게 된다면 필요할 것이라는 생각때문이었습니다. 아직 능력이 부족하여 유연성에 대한 측면을 고려하지 못한 것 같습니다.

- 도메인 패키지 아래에 profile 관련 구현을 한다는 말을 이해하지 못했습니다....;; 
프로필(현재 파일도메인)을 파일 패키지 아래에 두는게 아니라 멤버 패키지 아래로 옳기는게 적절하다는 의미인지 궁굼합니다!

2021-03-21 15:14 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyaapi/api/file/FileController.java
> +public class FileController {
인터페이스로 추상화하여 사용하는 이유 중 하나가 구현체가 달라졌을 때 쉽게 갈아끼우기 위해서인데,
만약 file 로 추상화를 해도 구현체가 프로필 업로드, 미션결과 캡쳐 업로드, 채팅방 사진 업로드이 세가지면 서로 구현체를 갈아끼울 일이 있을까요? 반면에 (그냥 예시) 프로필 업로드라는 인터페이스를 만들고 프로필 S3 업로드라는 구현체, 프로필 NAS 업로드라는 구현체, 프로필 mock 업로드라는 구현체 세가지가 있으면 서로 갈아끼울 일이 있을까요?

라는 시각으로 접근해보시면 좋을 것 같습니다.

네 적절한 의미 맞습니다. 저도 리뷰하면서 깊게 생각은 안해봐서 반박 의견 주시면 감사하겠습니다

2021-03-21 15:15 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/api/file/FileController.java
> +                fileType.equals("png")))) {
도메인 enum에 대한 관련 링크를 혹시 부탁 드려도 되나요??

자바 enum은 알겠지만 도메인 enum에 대한 검색을 검색 결과들이 와닿지않아서 잘 못 찾아 보고있었나 궁굼합니다!

2021-03-21 15:19 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyaapi/api/file/FileController.java
> +                fileType.equals("png")))) {
도메인 레이어에서 java enum 을 활용하여 타입을 정의하고 해당 타입을 활용하는 것을 뜻했습니다.

2021-03-22 05:21 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/domain/file/File.java
> +    private String nickName;
지금 구조로는 닉네임 수정이 이루어질 때에 문제가 발생할 것같고 앞선 논의 결과로 nickName조회자체가 불필요할 수 있을것 같아서 좀 수정이 필요한 부분같습니다!

2021-03-22 09:45 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/api/file/FileController.java
> +            return new ResponseEntity(new HttpHeaders(), HttpStatus.BAD_REQUEST);
이부분에 대해서는 오늘 밑각코시간에 잠시 의논한후에 반영하도록 하겠습니다.!

2021-03-23 06:14 UTC, Ilisha29 commented on src/test/java/com/sproutt/eussyaeussyaapi/api/file/FileControllerTest.java
> +public class FileControllerTest extends HeaderSetUpWithToken {
테스트에 필요한 토큰과 필요한 헤더를 만들어주는 클래스로써 @BeforeEach단계에서 setUpHeader()메소드를 호출하게 됩니다.

2021-03-26 14:54 UTC, hyukjin-lee approved these changes

2021-03-26 14:54 UTC, merged