[Back] 채팅 기능 및 관련 api 구현
sproutt/eussya-eussya-api pull request #142
Opened 2021-04-05 12:20 UTC by Bellroute

#### STOMP 기반 채팅 기능 구현
    - websocket 연결 요청 : GET "/ws-stomp"
    - pub endpoint : "/pub/chat/message"
    - sub endpoint : "/sub/chat/rooms/{room_id}"

#### 관련 도메인 설명
    - ChatRoom : 채팅방 정보 (id, type)
    - ChatRoomJoin : 채팅방-회원 간 연결 테이블 (id, chatRoom_id, member_id) => 다대다 연결관계 매핑 막기 위해
    - ChatMessage : 채팅 메세지 정보 (id, sender_id, room_id, message, time...)
![image](https://user-images.githubusercontent.com/41420639/113572191-bb5f4600-9652-11eb-948e-625ab011dba1.png)

#### 채팅 관련 api
    - 1대1 채팅방 정보 요청 : PUT "/chat/rooms/one-on-one"
        - 두 사용자가 db에 존재하는 사용자인지 체크
        - 두 사용자가 포함된 1대1 채팅방이 존재하는 경우 기존 채팅방 정보 리턴
        - 두 사용자가 포함된 1대1 채팅방이 존재하지 않는 경우 새로운 채팅방 생성 후 리턴
        
    - 채팅방 히스토리 요청 : GET "/chat/rooms/{chatRoomId}/messages"
        - 요청자가 채팅방 구성원이 맞는지 체크
        - 최근 시간 기준으로 정렬한 채팅 메세지를 30개 단위로 페이징 처리하여 리턴

2021-04-14 15:23 UTC, hyukjin-lee commented
pr description 에 적힌 그림이 다대다인 케이스가 다대일 케이스로 적힌게 좀 있는 것 같은데 확인 부탁드립니다

2021-04-14 15:36 UTC, hyukjin-lee requested changes
코드량이 많아서 내일 다시 보겠습니다.. 죄송

2021-04-14 15:36 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyaapi/api/chat/ChatController.java
> +    private final JwtHelper jwtHelper;
jwthelper 관련 코드는 interceptor 나 filter 같은걸로 aop스럽게 처리 못하려나요

2021-04-14 15:36 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyaapi/api/chat/ChatController.java
> +        messagingTemplate.convertAndSend("/sub/chat/rooms/" + message.getRoomId(), message);
chat message 가 저장되었는데 convertAndSend 에서 에러가 나면?

2021-04-14 15:36 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyaapi/api/chat/ChatController.java
> +                message.getMessage());
message validation 같은건 안해도 되려나요?

2021-04-14 15:36 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyaapi/api/chat/ChatController.java
> +        return new ResponseEntity<>(chatRoom.toResponseDTO(), headers, HttpStatus.OK);
domain model 에 toDTO 같은 코드는 지양하면 어떨까요?
가장 변경에 안전해야할 도메인이 DTO 의 변경에 의존성이 생기게 되지 않을까요?

2021-04-14 15:36 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyaapi/api/chat/ChatController.java
> +    public ResponseEntity<ChatRoomResponseDTO> requestOneOnOneChatRoom(@LoginMember MemberTokenCommand memberTokenCommand,
전체 채팅은 아직 구현이 안된거죠?

2021-04-14 15:36 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyaapi/api/config/StompHandler.java
> +        if (StompCommand.CONNECT == accessor.getCommand()) {
String 일 것 같은데 혹시 이렇게 비교하는게 맞는지 확인부탁드려요

2021-04-14 15:36 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyaapi/application/chat/ChatServiceImpl.java
> +import java.util.*;
wildcard import 적용되었네요

2021-04-14 15:36 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyaapi/application/chat/ChatServiceImpl.java
> +        chatRoomJoinRepository.save(new ChatRoomJoin(participant2, chatRoom));
saveAll(List.of(new Chat~~, new Chat~~) ?

2021-04-15 10:34 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/api/chat/ChatController.java
> +        Pageable pageable = PageRequest.of(page, 30, Sort.by("time").descending());
30페이지까지만 보여준다는 것 같은데 상수로 표현한다면 의미가 더 분명해서 좋을 것 같습니다!!

2021-04-15 10:54 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyaapi/application/chat/ChatServiceImpl.java
> +        List<ChatRoom> existedChatRooms = findExistedChatRooms(ChatRoomType.ONE_ON_ONE, participant1, participant2);
chatRooms나 chatRoomList로도 부족하지 않은 네이밍이 아닐까 조심스레 얘기해봅니다!

2022-01-05 09:41 UTC, closed without merging